name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.2.0
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  modal_progress_hud: ^0.1.3
  flushbar: ^1.10.4
  firebase_messaging: ^6.0.16
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.5
  provider: ^4.3.2
  flutter_simple_dependency_injection: ^1.0.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.1
  build_runner: ^1.10.4

flutter:
  uses-material-design: true

  assets:
  - images/
